server {
    listen 443 ssl;
    server_name localhost jetonpeche.fr;

    # Redirige tout le HTTP vers le HTTPS
    return 301 https://$host$request_uri;

    # Emplacement des certificats À L'INTÉRIEUR du conteneur
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # Optimisations SSL de base
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # Redirige vers le conteneur front
        proxy_pass http://front:80;
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api {
        # Redirige vers le conteneur api
        proxy_pass http://api:8080; 
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}